language: python

sudo: false

addons:
    apt:
        packages:
            - unzip
python:
    - "3.6.6"
    - "2.7.15"

before_script:

script:
    - "PYTHONPATH=`pwd`"
    - "cd ./db"
    - "sh unzip_and_split.sh"
    - "cd ${PYTHONPATH} && python main.py"

after_script:

#branches:
#    only:
#        - "master"
