language: python

sudo: false

addons:
    apt:
        packages:
            - unzip
python:
    - "3.6.6"
    - "2.7.15"

before_script:

script:
    - "unzip ./db/postcode.zip -d ./db/ && python main.py"

after_script:

#branches:
#    only:
#        - "master"
