language: python

python:
    - "3.6.6"
    - "2.7.15"

before_script:
    - "apt install unzip"

script:
    - "unzip ./db/postcode.zip && python main.py"

after_script:

#branches:
#    only:
#        - "master"
